Add return_truncated decode flag
davisp/jiffy pull request #158
Opened 2017-11-22 09:54 UTC by sargun

2017-11-22 19:05 UTC, davisp requested changes
The implementation looks great but I'm wondering what the use case is exactly? Is this to detect where there's broken JSON or something? Also not entirely certain it needs to be an option seeing as we could just make it the default. I've got two or three other breaking changes I'd like to make as well and then finally call it a 1.0 I'd be fine adding this to that list rather than making it an option if that seems more logical.

2017-11-22 19:05 UTC, davisp commented on c_src/decoder.c
> +        if (d->return_truncated)
You need to add braces around the bodies of this if/else statement.

2017-11-22 22:16 UTC, sargun commented
The use case is that I have a protocol which takes JSON over streaming sockets (TCP, websocket). JSON is basically the "framing" format. Because of the properties of the protocol, you can get partial frames. In that case, I know to go ahead and wait for more and add it to the buffer before trying to decode again. 

I know that JSX has a streaming API, but I personally find it really difficult to use, especially when my messages are <16KB. A simple decode, append, continue loop works just fine.

2017-11-22 22:35 UTC, davisp commented
That makes sense but with the return_trailer and existing trucated
exception I’m not seeing what the extra position is giving. Seems like it’d
always be the end of the binary no?


On Wed, Nov 22, 2017 at 4:16 PM Sargun Dhillon <notifications@github.com>
wrote:

> The use case is that I have a protocol which takes JSON over streaming
> sockets (TCP, websocket). JSON is basically the "framing" format. Because
> of the properties of the protocol, you can get partial frames. In that
> case, I know to go ahead and wait for more and add it to the buffer before
> trying to decode again.
>
> I know that JSX has a streaming API, but I personally find it really
> difficult to use, especially when my messages are <16KB. A simple decode,
> append, continue loop works just fine.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/davisp/jiffy/pull/158#issuecomment-346487711>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AABN2Usdu-86vmbHTaKXkW2jrdWDMeCPks5s5J01gaJpZM4QnIKW>
> .
>

2017-11-24 21:35 UTC, sargun commented
Yeah, I'd think so, the only reason I'm returning the extra position is because I wanted it to be as similar to the existing API mechanism as possible. I agree, it doesn't make a lot of sense, but I'd hate to break API backwards compatibility.

2017-11-25 22:22 UTC, sargun commented
Fixed the braces.

2017-12-04 05:00 UTC, sargun commented
How do you want to proceed?

2026-04-24 03:05 UTC, nickva commented
Wonder if there is still any interest in this. I am about to make a 2.0 release so am looking at old issues and pull requests. Since it's been about 9 years, I'll close the  PR but if there is still interest in it, please feel free to open it.

2026-04-24 03:05 UTC, closed without merging